///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace BlankTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the TrendyolRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("f4a15ca4-011e-45b3-ad75-5804f1445ba2")]
    public partial class TrendyolRepository : RepoGenBaseFolder
    {
        static TrendyolRepository instance = new TrendyolRepository();
        TrendyolRepositoryFolders.EnTrendUEruenlerTuerkiyeninOnlineAlAppFolder _entrendueruenlertuerkiyeninonlineal;

        /// <summary>
        /// Gets the singleton class instance representing the TrendyolRepository element repository.
        /// </summary>
        [RepositoryFolder("f4a15ca4-011e-45b3-ad75-5804f1445ba2")]
        public static TrendyolRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public TrendyolRepository() 
            : base("TrendyolRepository", "/", null, 0, false, "f4a15ca4-011e-45b3-ad75-5804f1445ba2", ".\\RepositoryImages\\TrendyolRepositoryf4a15ca4.rximgres")
        {
            _entrendueruenlertuerkiyeninonlineal = new TrendyolRepositoryFolders.EnTrendUEruenlerTuerkiyeninOnlineAlAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("f4a15ca4-011e-45b3-ad75-5804f1445ba2")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The EnTrendUEruenlerTuerkiyeninOnlineAl folder.
        /// </summary>
        [RepositoryFolder("fd8dad48-1889-49fe-a152-5fbae8930ec5")]
        public virtual TrendyolRepositoryFolders.EnTrendUEruenlerTuerkiyeninOnlineAlAppFolder EnTrendUEruenlerTuerkiyeninOnlineAl
        {
            get { return _entrendueruenlertuerkiyeninonlineal; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class TrendyolRepositoryFolders
    {
        /// <summary>
        /// The EnTrendUEruenlerTuerkiyeninOnlineAlAppFolder folder.
        /// </summary>
        [RepositoryFolder("fd8dad48-1889-49fe-a152-5fbae8930ec5")]
        public partial class EnTrendUEruenlerTuerkiyeninOnlineAlAppFolder : RepoGenBaseFolder
        {
            TrendyolRepositoryFolders.AccordionFolder _accordion;
            RepoItemInfo _girişyapInfo;
            RepoItemInfo _emailloginInfo;
            RepoItemInfo _passwordloginInfo;
            RepoItemInfo _loginbuttonInfo;
            RepoItemInfo _luetfengecerlibirepostaadresigirinInfo;
            RepoItemInfo _enterproductnameInfo;
            RepoItemInfo _searchproductInfo;
            RepoItemInfo _tshirtInfo;
            RepoItemInfo _addtocartInfo;
            RepoItemInfo _cartInfo;
            RepoItemInfo _cartitemInfo;
            RepoItemInfo _trendyolInfo;
            RepoItemInfo _fvrtbtnInfo;
            RepoItemInfo _favoritesInfo;
            RepoItemInfo _imgwrapperInfo;
            RepoItemInfo _secondproductInfo;
            RepoItemInfo _paymentInfo;
            RepoItemInfo _tshirt2Info;
            RepoItemInfo _yardımdestekInfo;
            RepoItemInfo _questionInfo;
            RepoItemInfo _httpscdndsmcdncomweblogotylogoInfo;
            RepoItemInfo _hesabımInfo;
            RepoItemInfo _cıkışyapInfo;
            RepoItemInfo _pagecontentInfo;
            RepoItemInfo _sepetionaylaInfo;

            /// <summary>
            /// Creates a new EnTrendUEruenlerTuerkiyeninOnlineAl  folder.
            /// </summary>
            public EnTrendUEruenlerTuerkiyeninOnlineAlAppFolder(RepoGenBaseFolder parentFolder) :
                    base("EnTrendUEruenlerTuerkiyeninOnlineAl", "/dom[@domain='www.trendyol.com']", parentFolder, 30000, null, false, "fd8dad48-1889-49fe-a152-5fbae8930ec5", "")
            {
                _accordion = new TrendyolRepositoryFolders.AccordionFolder(this);
                _girişyapInfo = new RepoItemInfo(this, "GirişYap", ".//div[#'account-navigation-container']/div/div[1]/?/?/p[@innertext='Giriş Yap']", ".//div[#'account-navigation-container']//p[@innertext='Giriş Yap']", 30000, null, "158b6fc5-6a1b-41ff-a041-19c32430b4d2");
                _emailloginInfo = new RepoItemInfo(this, "EmailLogin", ".//input[#'login-email']", ".//input[#'login-email']", 30000, null, "8b7d1a2e-475f-4819-8e4b-7e82f8ded8a9");
                _passwordloginInfo = new RepoItemInfo(this, "PasswordLogin", ".//input[#'login-password-input']", ".//input[#'login-password-input']", 30000, null, "ba5c1417-6191-40a3-8b33-fe106e472c6f");
                _loginbuttonInfo = new RepoItemInfo(this, "LoginButton", ".//div[#'login-register']//form[@action='https://www.trendyol.com/giris?cb=https%3A%2F%2Fwww.trendyol.com%2F']/button", ".//div[#'login-register']//form/button", 30000, null, "a7ceac7b-37a2-4678-9857-d1460f92fdb3");
                _luetfengecerlibirepostaadresigirinInfo = new RepoItemInfo(this, "LuetfenGecerliBirEPostaAdresiGirin", ".//div[#'error-box-wrapper']/span[@innertext>'Lütfen geçerli bir e-posta']", ".//div[#'error-box-wrapper']/span[@innertext>'Lütfen geçerli bir e-posta']", 30000, null, "c3474e51-2542-4872-b56b-0cd0be5ce14d");
                _enterproductnameInfo = new RepoItemInfo(this, "EnterProductName", ".//div[#'auto-complete-app']//input[@type='text']", ".//div[#'auto-complete-app']//input[@type='text']", 30000, null, "1f8a2085-b252-4836-8775-bb38e0a690fb");
                _searchproductInfo = new RepoItemInfo(this, "SearchProduct", ".//div[#'auto-complete-app']//i", ".//div[#'auto-complete-app']//i", 30000, null, "fc68de46-b1fb-4e56-8c36-ea439b2c7e83");
                _tshirtInfo = new RepoItemInfo(this, "Tshirt", ".//div[#'search-app']/div/div[1]/div[2]/div[2]/div/div[1]/?/?/a[@href>'https://www.trendyol.com/']/div[1]/div[2]/div[2]", ".//div[#'search-app']/div/div[1]/div[2]/div[2]/div/div[1]/div[1]/a[@href>'https://www.trendyol.com/']/div[1]/div[2]/div[2]", 30000, null, "cf4208d2-3f29-4f4e-be6e-45aafdf78374");
                _addtocartInfo = new RepoItemInfo(this, "AddToCart", ".//main[#'product-detail-app']/div/div[3]//button/div[@innertext='Sepete Ekle']", ".//main[#'product-detail-app']//div[@innertext='Sepete Ekle']", 30000, null, "1f3d55ed-f82c-4d6a-b516-99b543ebe5a4");
                _cartInfo = new RepoItemInfo(this, "Cart", ".//div[#'account-navigation-container']/div/div[2]/a[@href>'https://www.trendyol.com/']/p[@innertext='Sepetim']", ".//div[#'account-navigation-container']//p[@innertext='Sepetim']", 30000, null, "4d134731-d97b-48ee-b1d0-a0083c3042df");
                _cartitemInfo = new RepoItemInfo(this, "CartItem", ".//div[#'pb-container']/div/div[3]/div[2]", ".//div[#'pb-container']/div/div[3]/div[2]", 30000, null, "f11ad0b9-21fd-4520-a44d-c1f33e1ec2b8");
                _trendyolInfo = new RepoItemInfo(this, "Trendyol", ".//a[#'logo']/img[@alt='Trendyol']", ".//a[#'logo']/img[@alt='Trendyol']", 30000, null, "51feb4d2-acfe-46f3-b87e-27dc7e147d5f");
                _fvrtbtnInfo = new RepoItemInfo(this, "FvrtBtn", ".//div[#'search-app']/div/div[1]/div[2]/div[2]/div/div[5]/?/?/i", ".//div[#'search-app']/div/div[1]/div[2]/div[2]/div/div[5]/div[2]/i", 30000, null, "cab51549-7965-45ad-a398-baa4fdc0fa4c");
                _favoritesInfo = new RepoItemInfo(this, "Favorites", ".//div[#'account-navigation-container']/div/a[@href>'https://www.trendyol.com/']/?/?/p[@innertext='Favorilerim']", ".//div[#'account-navigation-container']//p[@innertext='Favorilerim']", 30000, null, "8547f76f-3f3a-4ae2-98dc-2f5c932ae1ed");
                _imgwrapperInfo = new RepoItemInfo(this, "ImgWrapper", ".//div[#'account-gw-favorites']/div/div[3]/div/div[1]/a[@href>'https://www.trendyol.com/']/div[1]", ".//div[#'account-gw-favorites']/div/div[3]/div/div[1]/a[@href>'https://www.trendyol.com/']/div[1]", 30000, null, "ddea020b-3309-4c5d-8d30-5f916c06bd15");
                _secondproductInfo = new RepoItemInfo(this, "SecondProduct", ".//main[#'product-detail-app']/div/aside[1]/div[2]/div/div/div/div[6]/?/?/a[@href>'https://www.trendyol.com/']/?/?/img[@src='https://cdn.dsmcdn.com/ty99/product/media/images/20210406/13/78188487/66369790/1/1_org_thumb.jpg']", ".//main[#'product-detail-app']//img[@src='https://cdn.dsmcdn.com/ty99/product/media/images/20210406/13/78188487/66369790/1/1_org_thumb.jpg']", 30000, null, "5e72d05e-0c8a-4511-a3b0-1b4767270f40");
                _paymentInfo = new RepoItemInfo(this, "Payment", ".//aside[#'CheckoutAside']/section[6]/a[@innertext='Ödeme Yap']", ".//aside[#'CheckoutAside']/section[6]/a[@innertext='Ödeme Yap']", 30000, null, "70141e78-4c4d-421a-8023-ec4e091c77e8");
                _tshirt2Info = new RepoItemInfo(this, "Tshirt2", ".//div[#'search-app']/div/div[1]/div[2]/div[2]/div/div[2]/?/?/a[@href>'https://www.trendyol.com/']/div[1]/div[2]/div[2]", ".//div[#'search-app']/div/div[1]/div[2]/div[2]/div/div[2]/div[1]/a[@href>'https://www.trendyol.com/']/div[1]/div[2]/div[2]", 30000, null, "3c5ceb30-993d-4dfc-8238-7e017fe98a1f");
                _yardımdestekInfo = new RepoItemInfo(this, "YardımDestek", ".//div[#'headerMain']//ul/?/?/a[@innertext='Yardım & Destek']", ".//div[#'headerMain']//a[@innertext='Yardım & Destek']", 30000, null, "3d5ac442-8d53-4a7c-86ca-1127d73e66b4");
                _questionInfo = new RepoItemInfo(this, "Question", ".//div[#'accordion']/div[1]", ".//div[#'accordion']/div[1]", 30000, null, "daac30c6-8efa-406b-814e-582c0c3085a0");
                _httpscdndsmcdncomweblogotylogoInfo = new RepoItemInfo(this, "HttpsCdnDsmcdnComWebLogoTyLogo", ".//header[#'paymentHeader']//img[@src='https://cdn.dsmcdn.com/web/logo/ty-logo.svg']", ".//header[#'paymentHeader']//img[@src='https://cdn.dsmcdn.com/web/logo/ty-logo.svg']", 30000, null, "313388a4-0857-4e87-9551-103ed52e241b");
                _hesabımInfo = new RepoItemInfo(this, "Hesabım", ".//div[#'account-navigation-container']/div/div[1]/?/?/p[@innertext='Hesabım']", ".//div[#'account-navigation-container']//p[@innertext='Hesabım']", 30000, null, "0a75f096-752c-42ed-9d8a-182efc10637a");
                _cıkışyapInfo = new RepoItemInfo(this, "CıkışYap", ".//div[#'account-navigation-container']/div/div[1]/div[2]/div/a[8]/p[@innertext='Çıkış Yap']", ".//div[#'account-navigation-container']//p[@innertext='Çıkış Yap']", 30000, null, "6f7dd680-e6af-42d5-9443-05c5e087be11");
                _pagecontentInfo = new RepoItemInfo(this, "PageContent", ".//div[#'container']/div/div[3]/div[2]", ".//div[#'container']/div/div[3]/div[2]", 30000, null, "d7cb1341-6ec3-472f-a1bd-1ea2b94ea292");
                _sepetionaylaInfo = new RepoItemInfo(this, "SepetiOnayla", ".//div[#'pb-container']/aside/div/div[1]/?/?/span[@innertext='Sepeti Onayla']", ".//div[#'pb-container']//span[@innertext='Sepeti Onayla']", 30000, null, "0298ec13-4440-443d-b2d6-3c3e54f697ee");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("fd8dad48-1889-49fe-a152-5fbae8930ec5")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("fd8dad48-1889-49fe-a152-5fbae8930ec5")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The GirişYap item.
            /// </summary>
            [RepositoryItem("158b6fc5-6a1b-41ff-a041-19c32430b4d2")]
            public virtual Ranorex.PTag GirişYap
            {
                get
                {
                    return _girişyapInfo.CreateAdapter<Ranorex.PTag>(true);
                }
            }

            /// <summary>
            /// The GirişYap item info.
            /// </summary>
            [RepositoryItemInfo("158b6fc5-6a1b-41ff-a041-19c32430b4d2")]
            public virtual RepoItemInfo GirişYapInfo
            {
                get
                {
                    return _girişyapInfo;
                }
            }

            /// <summary>
            /// The EmailLogin item.
            /// </summary>
            [RepositoryItem("8b7d1a2e-475f-4819-8e4b-7e82f8ded8a9")]
            public virtual Ranorex.InputTag EmailLogin
            {
                get
                {
                    return _emailloginInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The EmailLogin item info.
            /// </summary>
            [RepositoryItemInfo("8b7d1a2e-475f-4819-8e4b-7e82f8ded8a9")]
            public virtual RepoItemInfo EmailLoginInfo
            {
                get
                {
                    return _emailloginInfo;
                }
            }

            /// <summary>
            /// The PasswordLogin item.
            /// </summary>
            [RepositoryItem("ba5c1417-6191-40a3-8b33-fe106e472c6f")]
            public virtual Ranorex.InputTag PasswordLogin
            {
                get
                {
                    return _passwordloginInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The PasswordLogin item info.
            /// </summary>
            [RepositoryItemInfo("ba5c1417-6191-40a3-8b33-fe106e472c6f")]
            public virtual RepoItemInfo PasswordLoginInfo
            {
                get
                {
                    return _passwordloginInfo;
                }
            }

            /// <summary>
            /// The LoginButton item.
            /// </summary>
            [RepositoryItem("a7ceac7b-37a2-4678-9857-d1460f92fdb3")]
            public virtual Ranorex.ButtonTag LoginButton
            {
                get
                {
                    return _loginbuttonInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The LoginButton item info.
            /// </summary>
            [RepositoryItemInfo("a7ceac7b-37a2-4678-9857-d1460f92fdb3")]
            public virtual RepoItemInfo LoginButtonInfo
            {
                get
                {
                    return _loginbuttonInfo;
                }
            }

            /// <summary>
            /// The LuetfenGecerliBirEPostaAdresiGirin item.
            /// </summary>
            [RepositoryItem("c3474e51-2542-4872-b56b-0cd0be5ce14d")]
            public virtual Ranorex.SpanTag LuetfenGecerliBirEPostaAdresiGirin
            {
                get
                {
                    return _luetfengecerlibirepostaadresigirinInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The LuetfenGecerliBirEPostaAdresiGirin item info.
            /// </summary>
            [RepositoryItemInfo("c3474e51-2542-4872-b56b-0cd0be5ce14d")]
            public virtual RepoItemInfo LuetfenGecerliBirEPostaAdresiGirinInfo
            {
                get
                {
                    return _luetfengecerlibirepostaadresigirinInfo;
                }
            }

            /// <summary>
            /// The EnterProductName item.
            /// </summary>
            [RepositoryItem("1f8a2085-b252-4836-8775-bb38e0a690fb")]
            public virtual Ranorex.InputTag EnterProductName
            {
                get
                {
                    return _enterproductnameInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The EnterProductName item info.
            /// </summary>
            [RepositoryItemInfo("1f8a2085-b252-4836-8775-bb38e0a690fb")]
            public virtual RepoItemInfo EnterProductNameInfo
            {
                get
                {
                    return _enterproductnameInfo;
                }
            }

            /// <summary>
            /// The SearchProduct item.
            /// </summary>
            [RepositoryItem("fc68de46-b1fb-4e56-8c36-ea439b2c7e83")]
            public virtual Ranorex.ITag SearchProduct
            {
                get
                {
                    return _searchproductInfo.CreateAdapter<Ranorex.ITag>(true);
                }
            }

            /// <summary>
            /// The SearchProduct item info.
            /// </summary>
            [RepositoryItemInfo("fc68de46-b1fb-4e56-8c36-ea439b2c7e83")]
            public virtual RepoItemInfo SearchProductInfo
            {
                get
                {
                    return _searchproductInfo;
                }
            }

            /// <summary>
            /// The Tshirt item.
            /// </summary>
            [RepositoryItem("cf4208d2-3f29-4f4e-be6e-45aafdf78374")]
            public virtual Ranorex.DivTag Tshirt
            {
                get
                {
                    return _tshirtInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Tshirt item info.
            /// </summary>
            [RepositoryItemInfo("cf4208d2-3f29-4f4e-be6e-45aafdf78374")]
            public virtual RepoItemInfo TshirtInfo
            {
                get
                {
                    return _tshirtInfo;
                }
            }

            /// <summary>
            /// The AddToCart item.
            /// </summary>
            [RepositoryItem("1f3d55ed-f82c-4d6a-b516-99b543ebe5a4")]
            public virtual Ranorex.DivTag AddToCart
            {
                get
                {
                    return _addtocartInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The AddToCart item info.
            /// </summary>
            [RepositoryItemInfo("1f3d55ed-f82c-4d6a-b516-99b543ebe5a4")]
            public virtual RepoItemInfo AddToCartInfo
            {
                get
                {
                    return _addtocartInfo;
                }
            }

            /// <summary>
            /// The Cart item.
            /// </summary>
            [RepositoryItem("4d134731-d97b-48ee-b1d0-a0083c3042df")]
            public virtual Ranorex.PTag Cart
            {
                get
                {
                    return _cartInfo.CreateAdapter<Ranorex.PTag>(true);
                }
            }

            /// <summary>
            /// The Cart item info.
            /// </summary>
            [RepositoryItemInfo("4d134731-d97b-48ee-b1d0-a0083c3042df")]
            public virtual RepoItemInfo CartInfo
            {
                get
                {
                    return _cartInfo;
                }
            }

            /// <summary>
            /// The CartItem item.
            /// </summary>
            [RepositoryItem("f11ad0b9-21fd-4520-a44d-c1f33e1ec2b8")]
            public virtual Ranorex.DivTag CartItem
            {
                get
                {
                    return _cartitemInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The CartItem item info.
            /// </summary>
            [RepositoryItemInfo("f11ad0b9-21fd-4520-a44d-c1f33e1ec2b8")]
            public virtual RepoItemInfo CartItemInfo
            {
                get
                {
                    return _cartitemInfo;
                }
            }

            /// <summary>
            /// The Trendyol item.
            /// </summary>
            [RepositoryItem("51feb4d2-acfe-46f3-b87e-27dc7e147d5f")]
            public virtual Ranorex.ImgTag Trendyol
            {
                get
                {
                    return _trendyolInfo.CreateAdapter<Ranorex.ImgTag>(true);
                }
            }

            /// <summary>
            /// The Trendyol item info.
            /// </summary>
            [RepositoryItemInfo("51feb4d2-acfe-46f3-b87e-27dc7e147d5f")]
            public virtual RepoItemInfo TrendyolInfo
            {
                get
                {
                    return _trendyolInfo;
                }
            }

            /// <summary>
            /// The FvrtBtn item.
            /// </summary>
            [RepositoryItem("cab51549-7965-45ad-a398-baa4fdc0fa4c")]
            public virtual Ranorex.ITag FvrtBtn
            {
                get
                {
                    return _fvrtbtnInfo.CreateAdapter<Ranorex.ITag>(true);
                }
            }

            /// <summary>
            /// The FvrtBtn item info.
            /// </summary>
            [RepositoryItemInfo("cab51549-7965-45ad-a398-baa4fdc0fa4c")]
            public virtual RepoItemInfo FvrtBtnInfo
            {
                get
                {
                    return _fvrtbtnInfo;
                }
            }

            /// <summary>
            /// The Favorites item.
            /// </summary>
            [RepositoryItem("8547f76f-3f3a-4ae2-98dc-2f5c932ae1ed")]
            public virtual Ranorex.PTag Favorites
            {
                get
                {
                    return _favoritesInfo.CreateAdapter<Ranorex.PTag>(true);
                }
            }

            /// <summary>
            /// The Favorites item info.
            /// </summary>
            [RepositoryItemInfo("8547f76f-3f3a-4ae2-98dc-2f5c932ae1ed")]
            public virtual RepoItemInfo FavoritesInfo
            {
                get
                {
                    return _favoritesInfo;
                }
            }

            /// <summary>
            /// The ImgWrapper item.
            /// </summary>
            [RepositoryItem("ddea020b-3309-4c5d-8d30-5f916c06bd15")]
            public virtual Ranorex.DivTag ImgWrapper
            {
                get
                {
                    return _imgwrapperInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The ImgWrapper item info.
            /// </summary>
            [RepositoryItemInfo("ddea020b-3309-4c5d-8d30-5f916c06bd15")]
            public virtual RepoItemInfo ImgWrapperInfo
            {
                get
                {
                    return _imgwrapperInfo;
                }
            }

            /// <summary>
            /// The SecondProduct item.
            /// </summary>
            [RepositoryItem("5e72d05e-0c8a-4511-a3b0-1b4767270f40")]
            public virtual Ranorex.ImgTag SecondProduct
            {
                get
                {
                    return _secondproductInfo.CreateAdapter<Ranorex.ImgTag>(true);
                }
            }

            /// <summary>
            /// The SecondProduct item info.
            /// </summary>
            [RepositoryItemInfo("5e72d05e-0c8a-4511-a3b0-1b4767270f40")]
            public virtual RepoItemInfo SecondProductInfo
            {
                get
                {
                    return _secondproductInfo;
                }
            }

            /// <summary>
            /// The Payment item.
            /// </summary>
            [RepositoryItem("70141e78-4c4d-421a-8023-ec4e091c77e8")]
            public virtual Ranorex.ATag Payment
            {
                get
                {
                    return _paymentInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The Payment item info.
            /// </summary>
            [RepositoryItemInfo("70141e78-4c4d-421a-8023-ec4e091c77e8")]
            public virtual RepoItemInfo PaymentInfo
            {
                get
                {
                    return _paymentInfo;
                }
            }

            /// <summary>
            /// The Tshirt2 item.
            /// </summary>
            [RepositoryItem("3c5ceb30-993d-4dfc-8238-7e017fe98a1f")]
            public virtual Ranorex.DivTag Tshirt2
            {
                get
                {
                    return _tshirt2Info.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Tshirt2 item info.
            /// </summary>
            [RepositoryItemInfo("3c5ceb30-993d-4dfc-8238-7e017fe98a1f")]
            public virtual RepoItemInfo Tshirt2Info
            {
                get
                {
                    return _tshirt2Info;
                }
            }

            /// <summary>
            /// The YardımDestek item.
            /// </summary>
            [RepositoryItem("3d5ac442-8d53-4a7c-86ca-1127d73e66b4")]
            public virtual Ranorex.ATag YardımDestek
            {
                get
                {
                    return _yardımdestekInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The YardımDestek item info.
            /// </summary>
            [RepositoryItemInfo("3d5ac442-8d53-4a7c-86ca-1127d73e66b4")]
            public virtual RepoItemInfo YardımDestekInfo
            {
                get
                {
                    return _yardımdestekInfo;
                }
            }

            /// <summary>
            /// The Question item.
            /// </summary>
            [RepositoryItem("daac30c6-8efa-406b-814e-582c0c3085a0")]
            public virtual Ranorex.DivTag Question
            {
                get
                {
                    return _questionInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Question item info.
            /// </summary>
            [RepositoryItemInfo("daac30c6-8efa-406b-814e-582c0c3085a0")]
            public virtual RepoItemInfo QuestionInfo
            {
                get
                {
                    return _questionInfo;
                }
            }

            /// <summary>
            /// The HttpsCdnDsmcdnComWebLogoTyLogo item.
            /// </summary>
            [RepositoryItem("313388a4-0857-4e87-9551-103ed52e241b")]
            public virtual Ranorex.ImgTag HttpsCdnDsmcdnComWebLogoTyLogo
            {
                get
                {
                    return _httpscdndsmcdncomweblogotylogoInfo.CreateAdapter<Ranorex.ImgTag>(true);
                }
            }

            /// <summary>
            /// The HttpsCdnDsmcdnComWebLogoTyLogo item info.
            /// </summary>
            [RepositoryItemInfo("313388a4-0857-4e87-9551-103ed52e241b")]
            public virtual RepoItemInfo HttpsCdnDsmcdnComWebLogoTyLogoInfo
            {
                get
                {
                    return _httpscdndsmcdncomweblogotylogoInfo;
                }
            }

            /// <summary>
            /// The Hesabım item.
            /// </summary>
            [RepositoryItem("0a75f096-752c-42ed-9d8a-182efc10637a")]
            public virtual Ranorex.PTag Hesabım
            {
                get
                {
                    return _hesabımInfo.CreateAdapter<Ranorex.PTag>(true);
                }
            }

            /// <summary>
            /// The Hesabım item info.
            /// </summary>
            [RepositoryItemInfo("0a75f096-752c-42ed-9d8a-182efc10637a")]
            public virtual RepoItemInfo HesabımInfo
            {
                get
                {
                    return _hesabımInfo;
                }
            }

            /// <summary>
            /// The CıkışYap item.
            /// </summary>
            [RepositoryItem("6f7dd680-e6af-42d5-9443-05c5e087be11")]
            public virtual Ranorex.PTag CıkışYap
            {
                get
                {
                    return _cıkışyapInfo.CreateAdapter<Ranorex.PTag>(true);
                }
            }

            /// <summary>
            /// The CıkışYap item info.
            /// </summary>
            [RepositoryItemInfo("6f7dd680-e6af-42d5-9443-05c5e087be11")]
            public virtual RepoItemInfo CıkışYapInfo
            {
                get
                {
                    return _cıkışyapInfo;
                }
            }

            /// <summary>
            /// The PageContent item.
            /// </summary>
            [RepositoryItem("d7cb1341-6ec3-472f-a1bd-1ea2b94ea292")]
            public virtual Ranorex.DivTag PageContent
            {
                get
                {
                    return _pagecontentInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The PageContent item info.
            /// </summary>
            [RepositoryItemInfo("d7cb1341-6ec3-472f-a1bd-1ea2b94ea292")]
            public virtual RepoItemInfo PageContentInfo
            {
                get
                {
                    return _pagecontentInfo;
                }
            }

            /// <summary>
            /// The SepetiOnayla item.
            /// </summary>
            [RepositoryItem("0298ec13-4440-443d-b2d6-3c3e54f697ee")]
            public virtual Ranorex.SpanTag SepetiOnayla
            {
                get
                {
                    return _sepetionaylaInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The SepetiOnayla item info.
            /// </summary>
            [RepositoryItemInfo("0298ec13-4440-443d-b2d6-3c3e54f697ee")]
            public virtual RepoItemInfo SepetiOnaylaInfo
            {
                get
                {
                    return _sepetionaylaInfo;
                }
            }

            /// <summary>
            /// The Accordion folder.
            /// </summary>
            [RepositoryFolder("735f0e52-621d-4e60-ae11-5334feb6fe92")]
            public virtual TrendyolRepositoryFolders.AccordionFolder Accordion
            {
                get { return _accordion; }
            }
        }

        /// <summary>
        /// The AccordionFolder folder.
        /// </summary>
        [RepositoryFolder("735f0e52-621d-4e60-ae11-5334feb6fe92")]
        public partial class AccordionFolder : RepoGenBaseFolder
        {
            RepoItemInfo _ptagsatınaldığınızueruenlerueruendeInfo;
            RepoItemInfo _ptagsiparişdağıtımacıktığındakargofInfo;
            RepoItemInfo _ptagueruende24saattekargodayazısıvInfo;
            RepoItemInfo _ptagkargoyaverildiktensonrasiparişinInfo;

            /// <summary>
            /// Creates a new Accordion  folder.
            /// </summary>
            public AccordionFolder(RepoGenBaseFolder parentFolder) :
                    base("Accordion", ".//div[#'accordion']", parentFolder, 30000, null, false, "735f0e52-621d-4e60-ae11-5334feb6fe92", "")
            {
                _ptagsatınaldığınızueruenlerueruendeInfo = new RepoItemInfo(this, "PTagSatınAldığınızUeruenlerUeruenDe", "?/?/p[@innertext>'• Satın aldığınız ürünler']", "?/?/p[@innertext>'• Satın aldığınız ürünler']", 30000, null, "6a51081f-81f4-4ccd-8971-f84fe7a94ee4");
                _ptagsiparişdağıtımacıktığındakargofInfo = new RepoItemInfo(this, "PTagSiparişDağıtımaCıktığındaKargoF", "?/?/p[@innertext>'• Sipariş dağıtıma çıktığında']", "?/?/p[@innertext>'• Sipariş dağıtıma çıktığında']", 30000, null, "0cc1514b-1de5-4112-8137-2d161b9bc84c");
                _ptagueruende24saattekargodayazısıvInfo = new RepoItemInfo(this, "PTagUEruende24SaatteKargodaYazısıV", "?/?/p[@innertext>'• Üründe “24 saatte kargoda”']", "?/?/p[@innertext>'• Üründe “24 saatte kargoda”']", 30000, null, "e920f2db-f508-4fc6-84ee-7f5053204d0f");
                _ptagkargoyaverildiktensonrasiparişinInfo = new RepoItemInfo(this, "PTagKargoyaVerildiktenSonraSiparişin", "?/?/p[@innertext>'• Kargoya verildikten sonra']", "?/?/p[@innertext>'• Kargoya verildikten sonra']", 30000, null, "7437d66e-ff02-43cd-ae0f-b25f569fabcd");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("735f0e52-621d-4e60-ae11-5334feb6fe92")]
            public virtual Ranorex.DivTag Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("735f0e52-621d-4e60-ae11-5334feb6fe92")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The PTagSatınAldığınızUeruenlerUeruenDe item.
            /// </summary>
            [RepositoryItem("6a51081f-81f4-4ccd-8971-f84fe7a94ee4")]
            public virtual Ranorex.PTag PTagSatınAldığınızUeruenlerUeruenDe
            {
                get
                {
                    return _ptagsatınaldığınızueruenlerueruendeInfo.CreateAdapter<Ranorex.PTag>(true);
                }
            }

            /// <summary>
            /// The PTagSatınAldığınızUeruenlerUeruenDe item info.
            /// </summary>
            [RepositoryItemInfo("6a51081f-81f4-4ccd-8971-f84fe7a94ee4")]
            public virtual RepoItemInfo PTagSatınAldığınızUeruenlerUeruenDeInfo
            {
                get
                {
                    return _ptagsatınaldığınızueruenlerueruendeInfo;
                }
            }

            /// <summary>
            /// The PTagSiparişDağıtımaCıktığındaKargoF item.
            /// </summary>
            [RepositoryItem("0cc1514b-1de5-4112-8137-2d161b9bc84c")]
            public virtual Ranorex.PTag PTagSiparişDağıtımaCıktığındaKargoF
            {
                get
                {
                    return _ptagsiparişdağıtımacıktığındakargofInfo.CreateAdapter<Ranorex.PTag>(true);
                }
            }

            /// <summary>
            /// The PTagSiparişDağıtımaCıktığındaKargoF item info.
            /// </summary>
            [RepositoryItemInfo("0cc1514b-1de5-4112-8137-2d161b9bc84c")]
            public virtual RepoItemInfo PTagSiparişDağıtımaCıktığındaKargoFInfo
            {
                get
                {
                    return _ptagsiparişdağıtımacıktığındakargofInfo;
                }
            }

            /// <summary>
            /// The PTagUEruende24SaatteKargodaYazısıV item.
            /// </summary>
            [RepositoryItem("e920f2db-f508-4fc6-84ee-7f5053204d0f")]
            public virtual Ranorex.PTag PTagUEruende24SaatteKargodaYazısıV
            {
                get
                {
                    return _ptagueruende24saattekargodayazısıvInfo.CreateAdapter<Ranorex.PTag>(true);
                }
            }

            /// <summary>
            /// The PTagUEruende24SaatteKargodaYazısıV item info.
            /// </summary>
            [RepositoryItemInfo("e920f2db-f508-4fc6-84ee-7f5053204d0f")]
            public virtual RepoItemInfo PTagUEruende24SaatteKargodaYazısıVInfo
            {
                get
                {
                    return _ptagueruende24saattekargodayazısıvInfo;
                }
            }

            /// <summary>
            /// The PTagKargoyaVerildiktenSonraSiparişin item.
            /// </summary>
            [RepositoryItem("7437d66e-ff02-43cd-ae0f-b25f569fabcd")]
            public virtual Ranorex.PTag PTagKargoyaVerildiktenSonraSiparişin
            {
                get
                {
                    return _ptagkargoyaverildiktensonrasiparişinInfo.CreateAdapter<Ranorex.PTag>(true);
                }
            }

            /// <summary>
            /// The PTagKargoyaVerildiktenSonraSiparişin item info.
            /// </summary>
            [RepositoryItemInfo("7437d66e-ff02-43cd-ae0f-b25f569fabcd")]
            public virtual RepoItemInfo PTagKargoyaVerildiktenSonraSiparişinInfo
            {
                get
                {
                    return _ptagkargoyaverildiktensonrasiparişinInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
